using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Interface for special or combo behaviors that generate lightning strikes.
/// SpecialResolver uses this to gather all lightning strikes for the centralized clear action.
/// </summary>
public interface ILightningBehavior
{
    /// <summary>
    /// Indicates if this behavior triggers a line activation effect (e.g. screen darkens).
    /// </summary>
    bool HasLineActivation { get; }

    /// <summary>
    /// Returns the lightning strikes generated by this behavior at the given origin.
    /// </summary>
    IEnumerable<LightningLineStrike> GetLineStrikes(int originX, int originY);
}
