using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Interface for combo behaviors that generate lightning strikes.
/// SpecialResolver uses this to gather all lightning strikes for the combo's clear action.
/// </summary>
public interface ILightningComboBehavior
{
    /// <summary>
    /// Indicates if this combo triggers a line activation effect (e.g. screen darkens).
    /// </summary>
    bool HasLineActivation { get; }

    /// <summary>
    /// Returns the lightning strikes generated by this combo at the given origin.
    /// </summary>
    IEnumerable<LightningLineStrike> GetLineStrikes(int originX, int originY, TileSpecial a, TileSpecial b);
}
